In [1]:
# Create synthetic data with potential issues
data1 = {
    'ID': [1, 2, 3, 4, 5, 6, 7, 8],
    'Name': ['John', 'Alice', 'Bob', 'Charlie', 'Eva', 'Dave', 'Frank', 'Grace']
}

In [2]:
print(data1)

{'ID': [1, 2, 3, 4, 5, 6, 7, 8], 'Name': ['John', 'Alice', 'Bob', 'Charlie', 'Eva', 'Dave', 'Frank', 'Grace']}

In [11]:
import pandas as pd
data={'Age': [25, 25, '35', 40, 45, 50, 'nan','nan', 60],
    'Salary': [50000, 50000, 70000, 80000, 90000, 100000, 110000, 120000,100000],
    'Rating': [4.5, 4.5, 4.2, 3.9, 4.8, 5.0, 4.2, 'nan','nan']
}


# Save synthetic data to CSV file
df = pd.DataFrame(data)
df.to_csv('sample_data.csv', index=False)

In [12]:
import pandas as pd

# Load the CSV file
df = pd.read_csv('sample_data.csv')

# Display the original data
print("Original Data:")
print(df)

Original Data:
    Age  Salary  Rating
0  25.0   50000     4.5
1  25.0   50000     4.5
2  35.0   70000     4.2
3  40.0   80000     3.9
4  45.0   90000     4.8
5  50.0  100000     5.0
6   NaN  110000     4.2
7   NaN  120000     NaN
8  60.0  100000     NaN

In [13]:
# Data cleaning processes
df_cleaned = df.dropna()

In [14]:
print(df)

    Age  Salary  Rating
0  25.0   50000     4.5
1  25.0   50000     4.5
2  35.0   70000     4.2
3  40.0   80000     3.9
4  45.0   90000     4.8
5  50.0  100000     5.0
6   NaN  110000     4.2
7   NaN  120000     NaN
8  60.0  100000     NaN

In [15]:
print(df.duplicated())

0    False
1     True
2    False
3    False
4    False
5    False
6    False
7    False
8    False
dtype: bool

In [16]:
# Display the cleaned data
print("\nCleaned Data:")
print(df_cleaned)

Cleaned Data:
    Age  Salary  Rating
0  25.0   50000     4.5
1  25.0   50000     4.5
2  35.0   70000     4.2
3  40.0   80000     3.9
4  45.0   90000     4.8
5  50.0  100000     5.0